# Generated by Django 5.2.6 on 2025-09-11 11:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('session_data', models.JSONField(blank=True, null=True)),
                ('device_info', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
                ('users_scraped', models.IntegerField(default=0)),
                ('dms_sent', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('user_id', models.CharField(max_length=255)),
                ('biography', models.TextField(blank=True)),
                ('last_post_date', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('keywords', models.JSONField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_users', to='dmbot.account')),
            ],
        ),
    ]
