# Generated by Django 5.2.6 on 2025-09-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='relogin_attempt',
            field=models.IntegerField(default=0),
        ),
    ]
