# Generated by Django 5.2.6 on 2025-09-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmbot', '0002_account_relogin_attempt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='device_info',
            new_name='device_settings',
        ),
        migrations.AddField(
            model_name='account',
            name='account_age_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='daily_scrape_limit',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='warmed_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('scraping', 'Scraping'), ('rate_limited', 'Rate Limited'), ('error', 'Error'), ('warming_up', 'Warming Up')], default='idle', max_length=50),
        ),
    ]
