# Generated by Django 5.2.6 on 2025-09-16 10:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmbot', '0003_rename_device_info_account_device_settings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_filters', models.JSONField(default=dict)),
                ('total_sent', models.IntegerField(default=0)),
                ('responses_received', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DMTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template', models.TextField()),
                ('category', models.CharField(default='general', max_length=50)),
                ('success_rate', models.FloatField(default=0.0)),
                ('times_used', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='account',
            old_name='dms_sent',
            new_name='actions_this_hour',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='relogin_attempt',
            new_name='dms_sent_today',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='users_scraped',
            new_name='login_failures',
        ),
        migrations.RemoveField(
            model_name='account',
            name='session_id',
        ),
        migrations.AddField(
            model_name='account',
            name='daily_dm_limit',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='account',
            name='health_score',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='account',
            name='hour_reset',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='account',
            name='last_action_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='last_login_failure',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='last_reset',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='account',
            name='users_scraped_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='warmup_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alert',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dmbot.account'),
        ),
        migrations.AddField(
            model_name='alert',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='scrapeduser',
            name='category_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scrapeduser',
            name='dm_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_dms', to='dmbot.account'),
        ),
        migrations.AddField(
            model_name='scrapeduser',
            name='dm_response_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scrapeduser',
            name='dm_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scrapeduser',
            name='dm_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapeduser',
            name='engagement_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scrapeduser',
            name='follower_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapeduser',
            name='following_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapeduser',
            name='post_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapeduser',
            name='source_type',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapeduser',
            name='source_value',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='account_age_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='daily_scrape_limit',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('scraping', 'Scraping'), ('sending_dms', 'Sending DMs'), ('rate_limited', 'Rate Limited'), ('error', 'Error'), ('warming_up', 'Warming Up'), ('banned', 'Banned'), ('flagged', 'Flagged')], default='idle', max_length=50),
        ),
        migrations.AlterField(
            model_name='scrapeduser',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmbot.account'),
        ),
        migrations.AlterField(
            model_name='scrapeduser',
            name='keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='scrapeduser',
            name='user_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='scrapeduser',
            index=models.Index(fields=['is_active', 'dm_sent'], name='dmbot_scrap_is_acti_2c54bf_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapeduser',
            index=models.Index(fields=['profession', 'country'], name='dmbot_scrap_profess_390c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapeduser',
            index=models.Index(fields=['scraped_at'], name='dmbot_scrap_scraped_04d762_idx'),
        ),
        migrations.AddField(
            model_name='dmcampaign',
            name='accounts',
            field=models.ManyToManyField(related_name='campaigns', to='dmbot.account'),
        ),
        migrations.AddField(
            model_name='dmcampaign',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmbot.dmtemplate'),
        ),
    ]
