# Generated by Django 5.2.6 on 2025-09-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmbot', '0004_dmcampaign_dmtemplate_alter_alert_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeduser',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeduser',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
