# Generated by Django 5.2.6 on 2025-10-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmbot', '0005_scrapeduser_failure_reason_alter_scrapeduser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
