# Generated by Django 5.2.6 on 2025-10-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmbot', '0006_account_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeduser',
            name='details_fetched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='scrapeduser',
            index=models.Index(fields=['details_fetched'], name='dmbot_scrap_details_ae2a1d_idx'),
        ),
    ]
