# Generated by Django 5.2.6 on 2025-10-03 20:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmbot', '0007_scrapeduser_details_fetched_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_dms', to='dmbot.scrapeduser')),
                ('sender_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_logs', to='dmbot.account')),
            ],
        ),
    ]
