# Generated by Django 5.2.6 on 2025-10-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmbot', '0008_dmlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeduser',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('scraping', 'Scraping'), ('sending_dms', 'Sending DMs'), ('enriching_users', 'Enriching Users'), ('rate_limited', 'Rate Limited'), ('error', 'Error'), ('warming_up', 'Warming Up'), ('banned', 'Banned'), ('flagged', 'Flagged')], default='idle', max_length=50),
        ),
    ]
