# Generated by Django 5.2.6 on 2025-10-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmbot', '0009_scrapeduser_is_private_alter_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='task_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
