# Generated by Django 5.2.6 on 2025-10-05 07:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmbot', '0010_account_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(db_index=True, max_length=100)),
                ('hashtag', models.CharField(max_length=255)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_type', models.CharField(default='hashtag', max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_medias', to='dmbot.account')),
            ],
            options={
                'indexes': [models.Index(fields=['media_id', 'hashtag'], name='dmbot_proce_media_i_bbf33a_idx')],
                'unique_together': {('media_id', 'hashtag', 'account')},
            },
        ),
    ]
