# Generated by Django 5.2.6 on 2025-10-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmbot', '0011_processedmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMCsvUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('csv_file', models.FileField(upload_to='csv_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('total_processed', models.IntegerField(default=0)),
                ('total_successful', models.IntegerField(default=0)),
                ('total_failed', models.IntegerField(default=0)),
                ('total_skipped', models.IntegerField(default=0)),
            ],
        ),
    ]
