# Generated by Django 5.2.6 on 2025-10-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmbot', '0012_dmcsvupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmcsvupload',
            name='accounts',
            field=models.ManyToManyField(related_name='campaigns_csv', to='dmbot.account'),
        ),
    ]
